routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('proveedores', 'ProveedorController');

Route::resource('articulos', 'ArticuloController');

Route::resource('ventas', 'VentaController');

Route::resource('tipoArticulos', 'TipoArticuloController');

Route::resource('ivas', 'IvaController');

Route::resource('cuentaCorrientes', 'CuentaCorrienteController');

Route::resource('facturaVentas', 'FacturaVentaController');


Route::group(['prefix' => 'search'], function () {

    Route::any('/proveedor_nombre', 'SearchController@proveedor_nombre');
    Route::any('/articulo_nombre', 'SearchController@articulo_nombre');
    Route::any('/socio_nombre', 'SearchController@socio_nombre');
    Route::any('/tipoArticulo_nombre', 'SearchController@tipoArticulo_nombre');
    Route::any('/compras_categoria_nombre', 'SearchController@compras_categoria_nombre');

});

resources/views/proveedores/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Proveedor
        </h1>
    </section>
    <div class="content">
        <!--@include('adminlte-templates::common.errors')-->
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'proveedores.store']) !!}

                        @include('proveedores.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/proveedores/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Proveedor
        </h1>
   </section>
   <div class="content">
       <!--@include('adminlte-templates::common.errors')-->
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($proveedor, ['route' => ['proveedores.update', $proveedor->id], 'method' => 'patch']) !!}

                        @include('proveedores.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/proveedores/fields.blade.php
<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
    @if($errors->has('nombre'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('nombre')}}</strong>
        </span>
    @endif
</div>

<!-- Empresa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('empresa', 'Empresa:') !!}
    {!! Form::text('empresa', null, ['class' => 'form-control']) !!}
    @if($errors->has('empresa'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('empresa')}}</strong>
        </span>
    @endif
</div>

<!-- Direccion Field -->
<div class="form-group col-sm-3">
    {!! Form::label('direccion', 'Direccion:') !!}
    {!! Form::text('direccion', null, ['class' => 'form-control']) !!}
    @if($errors->has('direccion'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('direccion')}}</strong>
        </span>
    @endif
</div>

<!-- Telefono Field -->
<div class="form-group col-sm-3">
    {!! Form::label('telefono', 'Telefono:') !!}
    {!! Form::text('telefono', null, ['class' => 'form-control']) !!}
    @if($errors->has('telefono'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('telefono')}}</strong>
        </span>
    @endif
</div>


<!-- Cuit Field -->
<div class="form-group col-sm-3">
    {!! Form::label('cuit', 'Cuit:') !!}
    {!! Form::text('cuit', null, ['class' => 'form-control']) !!}
    @if($errors->has('cuit'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('cuit')}}</strong>
        </span>
    @endif
</div>

<!-- Email Field -->
<div class="form-group col-sm-3">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
    @if($errors->has('email'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('email')}}</strong>
        </span>
    @endif
</div>

<!-- Provincia Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('provincia_id', 'Provincia:') !!}
    {!! Form::select('provincia_id', $provincias, null, ['class' => 'form-control']) !!}
    @if($errors->has('provincia_id'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('provincia_id')}}</strong>
        </span>
    @endif
</div>

<!-- Localidad Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('localidad_id', 'Localidad:') !!}
    {!! Form::select('localidad_id', $localidades, null, ['class' => 'form-control']) !!}
    @if($errors->has('localidad_id'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('localidad_id')}}</strong>
        </span>
    @endif
</div>


<!-- Saldo Field -->
<div class="form-group col-sm-3">
    {!! Form::label('saldo', 'Saldo:') !!}
    {!! Form::text('saldo', null, ['class' => 'form-control']) !!}
    @if($errors->has('saldo'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('saldo')}}</strong>
        </span>
    @endif
</div>

<div class="form-group col-sm-3">
</div>

<!-- Otros Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('otros', 'Otros:') !!}
    {!! Form::textarea('otros', null, ['class' => 'form-control']) !!}
    @if($errors->has('otros'))
        <span class="invalid-feedback" role="alert" style="color: red; font-size: 9px">
            <strong>{{$errors->first('otros')}}</strong>
        </span>
    @endif
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('proveedores.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/proveedores/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Proveedores</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('proveedores.create') !!}">Agregar</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('proveedores.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/proveedores/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Proveedor
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('proveedores.show_fields')
                    <a href="{!! route('proveedores.index') !!}" class="btn btn-default">Volver</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/proveedores/show_fields.blade.php
<!-- Id Field -->
<!--<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $proveedor->id !!}</p>
</div>-->

<!-- Nombre Field -->
<div class="form-group col-sm-3">
    {!! Form::label('Nombre', 'Nombre:') !!}
    <p>{!! $proveedor->nombre !!}</p>
</div>

<!-- Empresa Field -->
<div class="form-group col-sm-3">
    {!! Form::label('Empresa', 'Empresa:') !!}
    <p>{!! $proveedor->empresa !!}</p>
</div>

<!-- Direccion Field -->
<div class="form-group col-sm-3">
    {!! Form::label('Direccion', 'Direccion:') !!}
    <p>{!! $proveedor->direccion !!}</p>
</div>

<!-- Telefono Field -->
<div class="form-group col-sm-3">
    {!! Form::label('Telefono', 'Telefono:') !!}
    <p>{!! $proveedor->telefono !!}</p>
</div>

<!-- Localidad Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('Localidad', 'Localidad:') !!}
    <p>{!! $proveedor->localidad_id !!}</p>
</div>

<!-- Provincia Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('Provincia', 'Provincia:') !!}
    <p>{!! $proveedor->provincia_id !!}</p>
</div>

<!-- Cuit Field -->
<div class="form-group col-sm-3" >
    {!! Form::label('Cuit', 'Cuit:') !!}
    <p>{!! $proveedor->cuit !!}</p>
</div>

<!-- Email Field -->
<div class="form-group col-sm-3">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $proveedor->email !!}</p>
</div>

<!-- Otros Field -->
<div class="form-group col-sm-3">
    {!! Form::label('otros', 'Otros:') !!}
    <p>{!! $proveedor->otros !!}</p>
</div>

<!-- Saldo Field -->
<div class="form-group col-sm-3">
    {!! Form::label('saldo', 'Saldo:') !!}
    <p>{!! $proveedor->saldo !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group col-sm-3">
    {!! Form::label('created_at', 'Creado:') !!}
    <p>{!! $proveedor->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group col-sm-3">
    {!! Form::label('updated_at', 'Actualizado:') !!}
    <p>{!! $proveedor->updated_at !!}</p>
</div>

resources/views/proveedores/table.blade.php
<table class="table table-responsive" id="proveedores-table">
    <thead>
        <tr>
            <th>Nombre</th>
        <th>Empresa</th>
        <th>Direccion</th>
        <th>Telefono</th>
        <th>Email</th>
        <th>Saldo</th>
        <th colspan="3">Acciones</th>
        </tr>
    </thead>
    <tbody>
    @foreach($proveedores as $proveedor)
        <tr>
            <td>{!! $proveedor->nombre !!}</td>
            <td>{!! $proveedor->empresa !!}</td>
            <td>{!! $proveedor->direccion !!}</td>
            <td>{!! $proveedor->telefono !!}</td>
            <td>{!! $proveedor->email !!}</td>
            <td>{!! $proveedor->saldo !!}</td>
            <td>
                {!! Form::open(['route' => ['proveedores.destroy', $proveedor->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('proveedores.show', [$proveedor->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('proveedores.edit', [$proveedor->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>