routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('proveedores', 'ProveedorController');

Route::resource('articulos', 'ArticuloController');

Route::resource('ventas', 'VentaController');

Route::resource('tipoArticulos', 'TipoArticuloController');

Route::resource('ivas', 'IvaController');

Route::resource('cuentaCorrientes', 'CuentaCorrienteController');

Route::resource('facturaVentas', 'FacturaVentaController');


Route::group(['prefix' => 'search'], function () {

    Route::any('/proveedor_nombre', 'SearchController@proveedor_nombre');
    Route::any('/articulo_nombre', 'SearchController@articulo_nombre');
    Route::any('/socio_nombre', 'SearchController@socio_nombre');
    Route::any('/tipoArticulo_nombre', 'SearchController@tipoArticulo_nombre');
    Route::any('/compras_categoria_nombre', 'SearchController@compras_categoria_nombre');

});

app/Models/FacturaVenta.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class FacturaVenta
 * @package App\Models
 * @version May 15, 2019, 5:36 pm -03
 *
 * @property string fecha
 * @property integer numero
 * @property string codigo
 * @property integer cliente_id
 * @property integer vendedor_id
 * @property string forma1
 * @property string forma2
 * @property float descu
 * @property float totalDescu
 * @property integer iva_id
 * @property float totalSIva
 * @property float exento
 */
class FacturaVenta extends Model
{
    use SoftDeletes;

    public $table = 'factura_ventas';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'fecha',
        'numero',
        'codigo',
        'cliente_id',
        'vendedor_id',
        'forma1',
        'forma2',
        'descu',
        'totalDescu',
        'iva_id',
        'totalSIva',
        'exento'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'fecha' => 'date',
        'numero' => 'integer',
        'codigo' => 'string',
        'cliente_id' => 'integer',
        'vendedor_id' => 'integer',
        'forma1' => 'string',
        'forma2' => 'string',
        'descu' => 'float',
        'totalDescu' => 'float',
        'iva_id' => 'integer',
        'totalSIva' => 'float',
        'exento' => 'float'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/FacturaVentaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateFacturaVentaRequest;
use App\Http\Requests\UpdateFacturaVentaRequest;
use App\Repositories\FacturaVentaRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class FacturaVentaController extends AppBaseController
{
    /** @var  FacturaVentaRepository */
    private $facturaVentaRepository;

    public function __construct(FacturaVentaRepository $facturaVentaRepo)
    {
        $this->facturaVentaRepository = $facturaVentaRepo;
    }

    /**
     * Display a listing of the FacturaVenta.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $facturaVentas = $this->facturaVentaRepository->all();

        return view('factura_ventas.index')
            ->with('facturaVentas', $facturaVentas);
    }

    /**
     * Show the form for creating a new FacturaVenta.
     *
     * @return Response
     */
    public function create()
    {
        return view('factura_ventas.create');
    }

    /**
     * Store a newly created FacturaVenta in storage.
     *
     * @param CreateFacturaVentaRequest $request
     *
     * @return Response
     */
    public function store(CreateFacturaVentaRequest $request)
    {
        $input = $request->all();

        $facturaVenta = $this->facturaVentaRepository->create($input);

        Flash::success('Factura Venta saved successfully.');

        return redirect(route('facturaVentas.index'));
    }

    /**
     * Display the specified FacturaVenta.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $facturaVenta = $this->facturaVentaRepository->find($id);

        if (empty($facturaVenta)) {
            Flash::error('Factura Venta not found');

            return redirect(route('facturaVentas.index'));
        }

        return view('factura_ventas.show')->with('facturaVenta', $facturaVenta);
    }

    /**
     * Show the form for editing the specified FacturaVenta.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $facturaVenta = $this->facturaVentaRepository->find($id);

        if (empty($facturaVenta)) {
            Flash::error('Factura Venta not found');

            return redirect(route('facturaVentas.index'));
        }

        return view('factura_ventas.edit')->with('facturaVenta', $facturaVenta);
    }

    /**
     * Update the specified FacturaVenta in storage.
     *
     * @param int $id
     * @param UpdateFacturaVentaRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFacturaVentaRequest $request)
    {
        $facturaVenta = $this->facturaVentaRepository->find($id);

        if (empty($facturaVenta)) {
            Flash::error('Factura Venta not found');

            return redirect(route('facturaVentas.index'));
        }

        $facturaVenta = $this->facturaVentaRepository->update($request->all(), $id);

        Flash::success('Factura Venta updated successfully.');

        return redirect(route('facturaVentas.index'));
    }

    /**
     * Remove the specified FacturaVenta from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $facturaVenta = $this->facturaVentaRepository->find($id);

        if (empty($facturaVenta)) {
            Flash::error('Factura Venta not found');

            return redirect(route('facturaVentas.index'));
        }

        $this->facturaVentaRepository->delete($id);

        Flash::success('Factura Venta deleted successfully.');

        return redirect(route('facturaVentas.index'));
    }
}

resources/views/factura_ventas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Factura Venta
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'facturaVentas.store']) !!}

                        @include('factura_ventas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/factura_ventas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Factura Venta
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($facturaVenta, ['route' => ['facturaVentas.update', $facturaVenta->id], 'method' => 'patch']) !!}

                        @include('factura_ventas.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/factura_ventas/fields.blade.php
<!-- Fecha Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha', 'Fecha:') !!}
    {!! Form::date('fecha', null, ['class' => 'form-control','id'=>'fecha']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#fecha').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: false
        })
    </script>
@endsection

<!-- Numero Field -->
<div class="form-group col-sm-6">
    {!! Form::label('numero', 'Numero:') !!}
    {!! Form::text('numero', null, ['class' => 'form-control']) !!}
</div>

<!-- Codigo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('codigo', 'Codigo:') !!}
    {!! Form::text('codigo', null, ['class' => 'form-control']) !!}
</div>

<!-- Cliente Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('cliente_id', 'Cliente Id:') !!}
    {!! Form::select('cliente_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Vendedor Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vendedor_id', 'Vendedor Id:') !!}
    {!! Form::select('vendedor_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Forma1 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('forma1', 'Forma1:') !!}
    {!! Form::text('forma1', null, ['class' => 'form-control']) !!}
</div>

<!-- Forma2 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('forma2', 'Forma2:') !!}
    {!! Form::text('forma2', null, ['class' => 'form-control']) !!}
</div>

<!-- Descu Field -->
<div class="form-group col-sm-6">
    {!! Form::label('descu', 'Descu:') !!}
    {!! Form::text('descu', null, ['class' => 'form-control']) !!}
</div>

<!-- Iva Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('iva_id', 'Iva Id:') !!}
    {!! Form::select('iva_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Totalsiva Field -->
<div class="form-group col-sm-6">
    {!! Form::label('totalSIva', 'Totalsiva:') !!}
    {!! Form::text('totalSIva', null, ['class' => 'form-control']) !!}
</div>

<!-- Exento Field -->
<div class="form-group col-sm-6">
    {!! Form::label('exento', 'Exento:') !!}
    {!! Form::text('exento', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('facturaVentas.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/factura_ventas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Factura Ventas</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('facturaVentas.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('factura_ventas.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/factura_ventas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Factura Venta
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('factura_ventas.show_fields')
                    <a href="{!! route('facturaVentas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/factura_ventas/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $facturaVenta->id !!}</p>
</div>

<!-- Fecha Field -->
<div class="form-group">
    {!! Form::label('fecha', 'Fecha:') !!}
    <p>{!! $facturaVenta->fecha !!}</p>
</div>

<!-- Numero Field -->
<div class="form-group">
    {!! Form::label('numero', 'Numero:') !!}
    <p>{!! $facturaVenta->numero !!}</p>
</div>

<!-- Codigo Field -->
<div class="form-group">
    {!! Form::label('codigo', 'Codigo:') !!}
    <p>{!! $facturaVenta->codigo !!}</p>
</div>

<!-- Cliente Id Field -->
<div class="form-group">
    {!! Form::label('cliente_id', 'Cliente Id:') !!}
    <p>{!! $facturaVenta->cliente_id !!}</p>
</div>

<!-- Vendedor Id Field -->
<div class="form-group">
    {!! Form::label('vendedor_id', 'Vendedor Id:') !!}
    <p>{!! $facturaVenta->vendedor_id !!}</p>
</div>

<!-- Forma1 Field -->
<div class="form-group">
    {!! Form::label('forma1', 'Forma1:') !!}
    <p>{!! $facturaVenta->forma1 !!}</p>
</div>

<!-- Forma2 Field -->
<div class="form-group">
    {!! Form::label('forma2', 'Forma2:') !!}
    <p>{!! $facturaVenta->forma2 !!}</p>
</div>

<!-- Descu Field -->
<div class="form-group">
    {!! Form::label('descu', 'Descu:') !!}
    <p>{!! $facturaVenta->descu !!}</p>
</div>

<!-- Totaldescu Field -->
<div class="form-group">
    {!! Form::label('totalDescu', 'Totaldescu:') !!}
    <p>{!! $facturaVenta->totalDescu !!}</p>
</div>

<!-- Iva Id Field -->
<div class="form-group">
    {!! Form::label('iva_id', 'Iva Id:') !!}
    <p>{!! $facturaVenta->iva_id !!}</p>
</div>

<!-- Totalsiva Field -->
<div class="form-group">
    {!! Form::label('totalSIva', 'Totalsiva:') !!}
    <p>{!! $facturaVenta->totalSIva !!}</p>
</div>

<!-- Exento Field -->
<div class="form-group">
    {!! Form::label('exento', 'Exento:') !!}
    <p>{!! $facturaVenta->exento !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $facturaVenta->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $facturaVenta->updated_at !!}</p>
</div>

resources/views/factura_ventas/table.blade.php
<table class="table table-responsive" id="facturaVentas-table">
    <thead>
        <tr>
            <th>Fecha</th>
        <th>Numero</th>
        <th>Codigo</th>
        <th>Cliente Id</th>
        <th>Vendedor Id</th>
        <th>Forma1</th>
        <th>Forma2</th>
        <th>Descu</th>
        <th>Totaldescu</th>
        <th>Iva Id</th>
        <th>Totalsiva</th>
        <th>Exento</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($facturaVentas as $facturaVenta)
        <tr>
            <td>{!! $facturaVenta->fecha !!}</td>
            <td>{!! $facturaVenta->numero !!}</td>
            <td>{!! $facturaVenta->codigo !!}</td>
            <td>{!! $facturaVenta->cliente_id !!}</td>
            <td>{!! $facturaVenta->vendedor_id !!}</td>
            <td>{!! $facturaVenta->forma1 !!}</td>
            <td>{!! $facturaVenta->forma2 !!}</td>
            <td>{!! $facturaVenta->descu !!}</td>
            <td>{!! $facturaVenta->totalDescu !!}</td>
            <td>{!! $facturaVenta->iva_id !!}</td>
            <td>{!! $facturaVenta->totalSIva !!}</td>
            <td>{!! $facturaVenta->exento !!}</td>
            <td>
                {!! Form::open(['route' => ['facturaVentas.destroy', $facturaVenta->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('facturaVentas.show', [$facturaVenta->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('facturaVentas.edit', [$facturaVenta->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>