routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('proveedores', 'ProveedorController');

Route::resource('articulos', 'ArticuloController');

Route::resource('ventas', 'VentaController');

Route::resource('tipoArticulos', 'TipoArticuloController');

Route::resource('ivas', 'IvaController');

Route::resource('cuentaCorrientes', 'CuentaCorrienteController');

Route::resource('facturaVentas', 'FacturaVentaController');


Route::group(['prefix' => 'search'], function () {

    Route::any('/proveedor_nombre', 'SearchController@proveedor_nombre');
    Route::any('/articulo_nombre', 'SearchController@articulo_nombre');
    Route::any('/socio_nombre', 'SearchController@socio_nombre');
    Route::any('/tipoArticulo_nombre', 'SearchController@tipoArticulo_nombre');
    Route::any('/compras_categoria_nombre', 'SearchController@compras_categoria_nombre');

});

app/Models/CuentaCorriente.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class CuentaCorriente
 * @package App\Models
 * @version May 8, 2019, 9:42 am -03
 *
 * @property string codigo
 * @property string fecha
 * @property string descripcion
 * @property integer cantidad
 * @property float importe
 * @property string tipo
 * @property float costo
 * @property integer articulo_id
 * @property float saldo
 * @property float ultimoPago
 * @property float ultimaCompra
 * @property integer cliente_id
 * @property integer recibo
 * @property string reciboTex
 * @property float costoReal
 */
class CuentaCorriente extends Model
{
    use SoftDeletes;

    public $table = 'cuenta_corrientes';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'codigo',
        'fecha',
        'descripcion',
        'cantidad',
        'importe',
        'tipo',
        'costo',
        'articulo_id',
        'saldo',
        'ultimoPago',
        'ultimaCompra',
        'cliente_id',
        'recibo',
        'reciboTex',
        'costoReal'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'codigo' => 'string',
        'fecha' => 'date',
        'descripcion' => 'string',
        'cantidad' => 'integer',
        'importe' => 'float',
        'tipo' => 'string',
        'costo' => 'float',
        'articulo_id' => 'integer',
        'saldo' => 'float',
        'ultimoPago' => 'float',
        'ultimaCompra' => 'float',
        'cliente_id' => 'integer',
        'recibo' => 'integer',
        'reciboTex' => 'string',
        'costoReal' => 'float'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function Socio(){
        return $this->belongsTo('App\Models\Socio');
    }
    
}

app/Http/Controllers/CuentaCorrienteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCuentaCorrienteRequest;
use App\Http\Requests\UpdateCuentaCorrienteRequest;
use App\Repositories\CuentaCorrienteRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CuentaCorrienteController extends AppBaseController
{
    /** @var  CuentaCorrienteRepository */
    private $cuentaCorrienteRepository;

    public function __construct(CuentaCorrienteRepository $cuentaCorrienteRepo)
    {
        $this->cuentaCorrienteRepository = $cuentaCorrienteRepo;
    }

    /**
     * Display a listing of the CuentaCorriente.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $cuentaCorrientes = $this->cuentaCorrienteRepository->all();

        return view('cuenta_corrientes.index')
            ->with('cuentaCorrientes', $cuentaCorrientes);
    }

    /**
     * Show the form for creating a new CuentaCorriente.
     *
     * @return Response
     */
    public function create()
    {
        return view('cuenta_corrientes.create');
    }

    /**
     * Store a newly created CuentaCorriente in storage.
     *
     * @param CreateCuentaCorrienteRequest $request
     *
     * @return Response
     */
    public function store(CreateCuentaCorrienteRequest $request)
    {
        $input = $request->all();

        $cuentaCorriente = $this->cuentaCorrienteRepository->create($input);

        Flash::success('Cuenta Corriente saved successfully.');

        return redirect(route('cuentaCorrientes.index'));
    }

    /**
     * Display the specified CuentaCorriente.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $cuentaCorriente = $this->cuentaCorrienteRepository->find($id);

        if (empty($cuentaCorriente)) {
            Flash::error('Cuenta Corriente not found');

            return redirect(route('cuentaCorrientes.index'));
        }

        return view('cuenta_corrientes.show')->with('cuentaCorriente', $cuentaCorriente);
    }

    /**
     * Show the form for editing the specified CuentaCorriente.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $cuentaCorriente = $this->cuentaCorrienteRepository->find($id);

        if (empty($cuentaCorriente)) {
            Flash::error('Cuenta Corriente not found');

            return redirect(route('cuentaCorrientes.index'));
        }

        return view('cuenta_corrientes.edit')->with('cuentaCorriente', $cuentaCorriente);
    }

    /**
     * Update the specified CuentaCorriente in storage.
     *
     * @param int $id
     * @param UpdateCuentaCorrienteRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCuentaCorrienteRequest $request)
    {
        $cuentaCorriente = $this->cuentaCorrienteRepository->find($id);

        if (empty($cuentaCorriente)) {
            Flash::error('Cuenta Corriente not found');

            return redirect(route('cuentaCorrientes.index'));
        }

        $cuentaCorriente = $this->cuentaCorrienteRepository->update($request->all(), $id);

        Flash::success('Cuenta Corriente updated successfully.');

        return redirect(route('cuentaCorrientes.index'));
    }

    /**
     * Remove the specified CuentaCorriente from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $cuentaCorriente = $this->cuentaCorrienteRepository->find($id);

        if (empty($cuentaCorriente)) {
            Flash::error('Cuenta Corriente not found');

            return redirect(route('cuentaCorrientes.index'));
        }

        $this->cuentaCorrienteRepository->delete($id);

        Flash::success('Cuenta Corriente deleted successfully.');

        return redirect(route('cuentaCorrientes.index'));
    }

    //Valida los datos que se ingresan en el formulario
    private function validarDatos(Request $request, $id = null){

        return $validator = Validator::make($request->all(),
            [
                'codigo' => 'string|unique:articulos',
                'fecha' => 'required|date|date_format:Y-m-d',
                'cliente' => 'required|string',
                'descripcion' => 'required|string',
                'cantidad' => 'required|string',
                'importe' => 'numeric',
                'stock' => 'required|string',
                'stockMinimo' => 'required|string',
                'ubicacion' => 'string',
                'costo' => 'string',
            ]);
    }
}

resources/views/cuenta_corrientes/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Cuenta Corriente
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'cuentaCorrientes.store']) !!}

                        @include('cuenta_corrientes.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cuenta_corrientes/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Cuenta Corriente
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($cuentaCorriente, ['route' => ['cuentaCorrientes.update', $cuentaCorriente->id], 'method' => 'patch']) !!}

                        @include('cuenta_corrientes.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/cuenta_corrientes/fields.blade.php
<!-- Codigo Field -->
<div class="form-group col-sm-3">
    {!! Form::label('codigo', 'Codigo:') !!}
    {!! Form::text('codigo', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Field -->
<div class="form-group col-sm-3">
    {!! Form::label('fecha', 'Fecha:') !!}
    {!! Form::date('fecha', null, ['class' => 'form-control','id'=>'fecha']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#fecha').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: false
        })
    </script>
@endsection

<!-- Cantidad Field -->
<div class="form-group col-sm-3">
    {!! Form::label('cantidad', 'Cantidad:') !!}
    {!! Form::text('cantidad', null, ['class' => 'form-control']) !!}
</div>

<!-- Importe Field -->
<div class="form-group col-sm-3">
    {!! Form::label('importe', 'Importe:') !!}
    {!! Form::text('importe', null, ['class' => 'form-control']) !!}
</div>

<!-- Tipo Field -->
<div class="form-group col-sm-3">
    {!! Form::label('tipo', 'Tipo:') !!}
    {!! Form::text('tipo', null, ['class' => 'form-control']) !!}
</div>

<!-- Costo Field -->
<div class="form-group col-sm-3">
    {!! Form::label('costo', 'Costo:') !!}
    {!! Form::text('costo', null, ['class' => 'form-control']) !!}
</div>

<!-- Articulo Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('articulo_id', 'Articulo Id:') !!}
    {!! Form::select('articulo_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Saldo Field -->
<div class="form-group col-sm-3">
    {!! Form::label('saldo', 'Saldo:') !!}
    {!! Form::text('saldo', null, ['class' => 'form-control']) !!}
</div>

<!-- Ultimopago Field -->
<div class="form-group col-sm-3">
    {!! Form::label('ultimoPago', 'Ultimopago:') !!}
    {!! Form::text('ultimoPago', null, ['class' => 'form-control']) !!}
</div>

<!-- Ultimacompra Field -->
<div class="form-group col-sm-3">
    {!! Form::label('ultimaCompra', 'Ultimacompra:') !!}
    {!! Form::text('ultimaCompra', null, ['class' => 'form-control']) !!}
</div>

<!-- Cliente Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('cliente_id', 'Cliente Id:') !!}
    {!! Form::select('cliente_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Recibo Field -->
<div class="form-group col-sm-3">
    {!! Form::label('recibo', 'Recibo:') !!}
    {!! Form::text('recibo', null, ['class' => 'form-control']) !!}
</div>

<!-- Recibotex Field -->
<div class="form-group col-sm-3">
    {!! Form::label('reciboTex', 'Recibotex:') !!}
    {!! Form::text('reciboTex', null, ['class' => 'form-control']) !!}
</div>

<!-- Costoreal Field -->
<div class="form-group col-sm-3">
    {!! Form::label('costoReal', 'Costoreal:') !!}
    {!! Form::text('costoReal', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('cuentaCorrientes.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/cuenta_corrientes/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Cuenta Corrientes</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('cuentaCorrientes.create') !!}">Agregar</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('cuenta_corrientes.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/cuenta_corrientes/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Cuenta Corriente
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('cuenta_corrientes.show_fields')
                    <a href="{!! route('cuentaCorrientes.index') !!}" class="btn btn-default">Volver</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cuenta_corrientes/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $cuentaCorriente->id !!}</p>
</div>

<!-- Codigo Field -->
<div class="form-group">
    {!! Form::label('codigo', 'Codigo:') !!}
    <p>{!! $cuentaCorriente->codigo !!}</p>
</div>

<!-- Fecha Field -->
<div class="form-group">
    {!! Form::label('fecha', 'Fecha:') !!}
    <p>{!! $cuentaCorriente->fecha !!}</p>
</div>

<!-- Descripcion Field -->
<div class="form-group">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    <p>{!! $cuentaCorriente->descripcion !!}</p>
</div>

<!-- Cantidad Field -->
<div class="form-group">
    {!! Form::label('cantidad', 'Cantidad:') !!}
    <p>{!! $cuentaCorriente->cantidad !!}</p>
</div>

<!-- Importe Field -->
<div class="form-group">
    {!! Form::label('importe', 'Importe:') !!}
    <p>{!! $cuentaCorriente->importe !!}</p>
</div>

<!-- Tipo Field -->
<div class="form-group">
    {!! Form::label('tipo', 'Tipo:') !!}
    <p>{!! $cuentaCorriente->tipo !!}</p>
</div>

<!-- Costo Field -->
<div class="form-group">
    {!! Form::label('costo', 'Costo:') !!}
    <p>{!! $cuentaCorriente->costo !!}</p>
</div>

<!-- Articulo Id Field -->
<div class="form-group">
    {!! Form::label('articulo_id', 'Articulo Id:') !!}
    <p>{!! $cuentaCorriente->articulo_id !!}</p>
</div>

<!-- Saldo Field -->
<div class="form-group">
    {!! Form::label('saldo', 'Saldo:') !!}
    <p>{!! $cuentaCorriente->saldo !!}</p>
</div>

<!-- Ultimopago Field -->
<div class="form-group">
    {!! Form::label('ultimoPago', 'Ultimopago:') !!}
    <p>{!! $cuentaCorriente->ultimoPago !!}</p>
</div>

<!-- Ultimacompra Field -->
<div class="form-group">
    {!! Form::label('ultimaCompra', 'Ultimacompra:') !!}
    <p>{!! $cuentaCorriente->ultimaCompra !!}</p>
</div>

<!-- Cliente Id Field -->
<div class="form-group">
    {!! Form::label('cliente_id', 'Cliente Id:') !!}
    <p>{!! $cuentaCorriente->cliente_id !!}</p>
</div>

<!-- Recibo Field -->
<div class="form-group">
    {!! Form::label('recibo', 'Recibo:') !!}
    <p>{!! $cuentaCorriente->recibo !!}</p>
</div>

<!-- Recibotex Field -->
<div class="form-group">
    {!! Form::label('reciboTex', 'Recibotex:') !!}
    <p>{!! $cuentaCorriente->reciboTex !!}</p>
</div>

<!-- Costoreal Field -->
<div class="form-group">
    {!! Form::label('costoReal', 'Costoreal:') !!}
    <p>{!! $cuentaCorriente->costoReal !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $cuentaCorriente->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $cuentaCorriente->updated_at !!}</p>
</div>

resources/views/cuenta_corrientes/table.blade.php
<table class="table table-responsive" id="cuentaCorrientes-table">
    <thead>
        <tr>
        <th>Fecha</th>
        <th>Cliente</th>
        <th>Descripcion</th>
        <th>Importe</th>
        <th>Saldo</th>
        <th>Ultimo pago</th>
        <th>Ultima compra</th>
         <th colspan="3">Acciones</th>
        </tr>
    </thead>
    <tbody>
    @foreach($cuentaCorrientes as $cuentaCorriente)
        <tr>
            <td>{!! $cuentaCorriente->fecha !!}</td>
            <td>{!! $cuentaCorriente->cliente_id !!}</td>
            <td>{!! $cuentaCorriente->descripcion !!}</td>
            <td>{!! $cuentaCorriente->importe !!}</td>
            <td>{!! $cuentaCorriente->saldo !!}</td>
            <td>{!! $cuentaCorriente->ultimoPago !!}</td>
            <td>{!! $cuentaCorriente->ultimaCompra !!}</td>
            <td>
                {!! Form::open(['route' => ['cuentaCorrientes.destroy', $cuentaCorriente->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('cuentaCorrientes.show', [$cuentaCorriente->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('cuentaCorrientes.edit', [$cuentaCorriente->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Está Seguro?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>